spring.application.name=DocuspaceApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/docu_space_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.security.user.name=username
spring.security.user.password=password

logging.level.org.springframework.security=DEBUG

app.jwt.secret=TXlTdXBlclNlY3JldEtleUZvckRvY3VTcGFjZUFwcGxpY2F0aW9uMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
app.jwt.expiration=86400000