spring.application.name=DocuspaceApplication
spring.datasource.url=${SPRING_DATASOURCE_URL_DEV}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME_DEV}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_DEV}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=${SPRING_USERNAME_DEV}
spring.security.user.password=${SPRING_PASSWORD_DEV}

logging.level.org.springframework.security=DEBUG

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

spring.ai.openai.api-key=${OPEN_AI_KEY}